<?php
/* vim: set expandtab tabstop=4 shiftwidth=4: */

/**
 * PHP version 5.3
 *
 * Copyright (c) 2011 KUBO Atsuhiro <kubo@iteman.jp>,
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * @package    PieceMakegoodBundle
 * @copyright  2011 KUBO Atsuhiro <kubo@iteman.jp>
 * @license    http://www.opensource.org/licenses/bsd-license.php  New BSD License
 * @version    Release: @package_version@
 * @since      File available since Release 0.1.0
 */

namespace Piece\Bundle\MakegoodBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

use Piece\Bundle\MakegoodBundle\Response\Chunk;
use Piece\Bundle\MakegoodBundle\Response\ChunkContainer;
use Piece\Bundle\MakegoodBundle\Response\ChunkResponse;

/**
 * @package    PieceMakegoodBundle
 * @copyright  2011 KUBO Atsuhiro <kubo@iteman.jp>
 * @license    http://www.opensource.org/licenses/bsd-license.php  New BSD License
 * @version    Release: @package_version@
 * @since      Class available since Release 0.1.0
 */
class TestRunController extends Controller implements ChunkContainer
{
    protected $resultAsJSON = array(
"{\"testsuites\": null}",
"{\"testsuite\": {\"name\": \"The test suite generated by Stagehand_TestRunner\", \"tests\": 9}}",
"{\"testsuite\": {\"name\": \"Stagehand_TestRunner_PHPUnitPassTest\", \"tests\": 3, \"file\": \"/path/to/PHPUnitPassTest.php\"}}",
"{\"testcase\": {\"name\": \"passWithAnAssertion\", \"class\": \"Stagehand_TestRunner_PHPUnitPassTest\", \"file\": \"/path/to/PHPUnitPassTest.php\", \"line\": 54}}",
"{\"/testcase\": null}",
"{\"testcase\": {\"name\": \"passWithMultipleAssertions\", \"class\": \"Stagehand_TestRunner_PHPUnitPassTest\", \"file\": \"/path/to/PHPUnitPassTest.php\", \"line\":62}}",
"{\"/testcase\": null}",
"{\"testcase\": {\"name\": \"日本語を使用できる\", \"class\": \"Stagehand_TestRunner_PHPUnitPassTest\", \"file\": \"/path/to/PHPUnitPassTest.php\", \"line\": 71}}",
"{\"/testcase\": null}",
"{\"/testsuite\": null}",
"{\"testsuite\": {\"name\": \"Stagehand_TestRunner_PHPUnitFailureTest\", \"tests\": 1, \"file\": \"/path/to/PHPUnitFailureTest.php\"}}",
"{\"testcase\": {\"name\": \"isFailure\", \"class\": \"Stagehand_TestRunner_PHPUnitFailureTest\", \"file\": \"/path/to/PHPUnitFailureTest.php\", \"line\": 54}}",
"{\"failure\": {\"type\": \"PHPUnit_Framework_ExpectationFailedException\", \"file\": \"/path/to/PHPUnitFailureTest.php\", \"line\": 56, \"message\": \"Stagehand_TestRunner_PHPUnitFailureTest::isFailure&#10;&#10;This is an error message.&#10;Failed asserting that &lt;boolean:false&gt; is true.&#10;&#10;\", \"trace\": \"Stagehand_TestRunner_PHPUnitFailureTest::isFailure&#10;&#10;This is an error message.&#10;Failed asserting that &lt;boolean:false&gt; is true.&#10;&#10;/path/to/PHPUnitFailureTest.php:56&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/Runner/PHPUnitRunner.php:116&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/TestRunner.php:79&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/TestRunnerCLIController.php:331&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/TestRunnerCLIController.php:181&#10;/home/iteman/site-php/PEAR/Stagehand/CLIController.php:101&#10;/home/iteman/GITREPOS/stagehand-testrunner/bin/phpunitrunner:77&#10;\"}}",
"{\"/failure\": null}",
"{\"/testcase\": null}",
"{\"/testsuite\": null}",
"{\"testsuite\": {\"name\": \"Stagehand_TestRunner_PHPUnitErrorTest\", \"tests\": 1, \"file\": \"/path/to/PHPUnitErrorTest.php\"}}",
"{\"testcase\": {\"name\": \"isError\", \"class\": \"Stagehand_TestRunner_PHPUnitErrorTest\", \"file\": \"/path/to/PHPUnitErrorTest.php\",  \"line\": 54}}",
"{\"error\": {\"type\": \"PHPUnit_Framework_Error_Notice\", \"file\": \"/path/to/PHPUnitErrorTest.php\", \"line\": 56, \"message\": \"Stagehand_TestRunner_PHPUnitErrorTest::isError&#10;&#10;Undefined property: Stagehand_TestRunner_PHPUnitErrorTest::\$foo&#10;&#10;\", \"trace\": \"Stagehand_TestRunner_PHPUnitErrorTest::isError&#10;&#10;Undefined property: Stagehand_TestRunner_PHPUnitErrorTest::\$foo&#10;&#10;/path/to/PHPUnitErrorTest.php:56&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/Runner/PHPUnitRunner.php:116&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/TestRunner.php:79&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/TestRunnerCLIController.php:331&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/TestRunnerCLIController.php:181&#10;/home/iteman/site-php/PEAR/Stagehand/CLIController.php:101&#10;/home/iteman/GITREPOS/stagehand-testrunner/bin/phpunitrunner:77&#10;\"}}",
"{\"/error\": null}",
"{\"/testcase\": null}",
"{\"/testsuite\": null}",
"{\"testsuite\": {\"name\": \"Stagehand_TestRunner_PHPUnitDataProviderTest\", \"tests\": 4, \"file\": \"/path/to/PHPUnitDataProviderTest.php\"}}",
"{\"testsuite\": {\"name\": \"passWithDataProvider\", \"tests\": 4, \"file\": \"/path/to/PHPUnitDataProviderTest.php\"}}",
"{\"testcase\": {\"name\": \"passWithDataProvider with data set #0\", \"class\": \"Stagehand_TestRunner_PHPUnitDataProviderTest\", \"file\": \"/path/to/PHPUnitDataProviderTest.php\", \"line\": 53}}",
"{\"/testcase\": null}",
"{\"testcase\": {\"name\": \"passWithDataProvider with data set #1\", \"class\": \"Stagehand_TestRunner_PHPUnitDataProviderTest\", \"file\": \"/path/to/PHPUnitDataProviderTest.php\", \"line\": 53}}",
"{\"/testcase\": null}",
"{\"testcase\": {\"name\": \"passWithDataProvider with data set #2\", \"class\": \"Stagehand_TestRunner_PHPUnitDataProviderTest\", \"file\": \"/path/to/PHPUnitDataProviderTest.php\", \"line\": 53}}",
"{\"/testcase\": null}",
"{\"testcase\": {\"name\": \"passWithDataProvider with data set #3\", \"class\": \"Stagehand_TestRunner_PHPUnitDataProviderTest\", \"file\": \"/path/to/PHPUnitDataProviderTest.php\", \"line\": 53}}",
"{\"failure\": {\"type\": \"PHPUnit_Framework_ExpectationFailedException\", \"file\": \"/path/to/PHPUnitDataProviderTest.php\", \"line\": 55, \"message\": \"Stagehand_TestRunner_PHPUnitDataProviderTest::passWithDataProvider with data set #3 (1, 1, 3)&#10;&#10;Failed asserting that &lt;integer:2&gt; matches expected &lt;integer:3&gt;.&#10;&#10;\", \"trace\": \"Stagehand_TestRunner_PHPUnitDataProviderTest::passWithDataProvider with data set #3 (1, 1, 3)&#10;&#10;Failed asserting that &lt;integer:2&gt; matches expected &lt;integer:3&gt;.&#10;&#10;/path/to/PHPUnitDataProviderTest.php:55&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/Runner/PHPUnitRunner.php:116&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/TestRunner.php:79&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/TestRunnerCLIController.php:331&#10;/home/iteman/GITREPOS/stagehand-testrunner/src/Stagehand/TestRunner/TestRunnerCLIController.php:181&#10;/home/iteman/site-php/PEAR/Stagehand/CLIController.php:101&#10;/home/iteman/GITREPOS/stagehand-testrunner/bin/phpunitrunner:77&#10;\"}}",
"{\"/failure\": null}",
"{\"/testcase\": null}",
"{\"/testsuite\": null}",
"{\"/testsuite\": null}",
"{\"/testsuite\": null}",
"{\"/testsuites\": null}",
);
    protected $currentChunkIndex = 0;
    protected $appendingData;

    public function __construct()
    {
        $this->appendingData = str_repeat(' ', 1024);
    }

    /**
     * {@inheritdoc}
     */
    public function getChunk()
    {
        if (count($this->resultAsJSON) == $this->currentChunkIndex + 1) {
            $isLast = true;
        } else {
            $isLast = false;
        }

        $resultFragment = base64_encode($this->resultAsJSON[ $this->currentChunkIndex ]);
        $data = sprintf('%d;%s;%s', strlen($resultFragment), $resultFragment, $this->appendingData);
        ++$this->currentChunkIndex;
        return new Chunk($data, $isLast);
    }

    public function runAction()
    {
    }

    public function showAction($testRunID)
    {
        $this->container->get('profiler')->disable();
        return new ChunkResponse($this, 200, array('Content-Type' => 'application/json'));
    }
}

/*
 * Local Variables:
 * mode: php
 * coding: utf-8
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * indent-tabs-mode: nil
 * End:
 */
